### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ethindp** [cupcakearmy/autorestic#89]
**Describe the bug**

After a few runs of autorestic, I receive this panic and I can no longer use the program.

**Expected behavior**

This should *never* happen.

**Environment**
 - OS: Arch Linux
 - Version: N/A

**Additional context**

The full backtrace is as follows:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7edbf9]

goroutine 1 [running]:
github.com/cupcakearmy/autorestic/internal.GetAllOrSelected(0xb8a0a0, 0x0, 0x0, 0x4aba2a, 0x203000, 0x203000, 0x203000)
	/home/ethin/go/pkg/mod/github.com/cupcakearmy/autorestic@v1.1.1/internal/config.go:157 +0x659
github.com/cupcakearmy/autorestic/cmd.glob..func1(0xb8a0a0, 0xc000047380, 0x0, 0x1)
	/home/ethin/go/pkg/mod/github.com/cupcakearmy/autorestic@v1.1.1/cmd/backup.go:22 +0x9d
github.com/spf13/cobra.(*Command).execute(0xb8a0a0, 0xc000047370, 0x1, 0x1, 0xb8a0a0, 0xc000047370)
	/home/ethin/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xb8a5a0, 0xb4b4d8, 0x94f570, 0x942128)
	/home/ethin/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/ethin/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cupcakearmy/autorestic/cmd.Execute()
	/home/ethin/go/pkg/mod/github.com/cupcakearmy/autorestic@v1.1.1/cmd/root.go:33 +0x2d
main.main()
	/home/ethin/go/pkg/mod/github.com/cupcakearmy/autorestic@v1.1.1/main.go:41 +0x2a
```

**Comment by ethindp** [comment]
I accidentally included some extraneous terminal output. Edited the first comment to get rid of that. Apologies. (I did try reinstalling with `go install` but I get the same behaviour.)

**Comment by cupcakearmy** [comment]
that is interesting. 

Can you maybe post your redacted config?

**Comment by ethindp** [comment]
Sorry for not replying to this issue sooner -- I got majorly distracted. My redacted config is below:

```yaml
backends:
  boot:
    type: b2
    path: ethins-computer-backups:system76-lemur/boot
    key: 
    env:
      b2_account_id: 
      b2_account_key: 
  etc:
    type: b2
    path: ethins-computer-backups:system76-lemur/etc
    key: 
    env:
      b2_account_id: 
      b2_account_key: 
  home:
    type: b2
    path: ethins-computer-backups:system76-lemur/home
    key: 
    env:
      b2_account_id: 
      b2_account_key: 
  mnt:
    type: b2
    path: ethins-computer-backups:system76-lemur/mnt
    key: 
    env:
      b2_account_id: 
      b2_account_key: 
locations:
  boot:
    from: /boot
    to:
    - boot
  etc:
    from: /etc
    to:
    - etc
  hdd:
    from: /mnt
    to:
    - mnt
    hooks:
        before:
                - mount /dev/disk/by-id/ata-ST2000LM015-2E8174_WDZ2790S-part1 /mnt
        after:
                - umount /mnt
  home:
    from: /home
    to:
    - home
    hooks:
      before:
        - echo "Generating package list"
        - yay -Qqe > $HOME/pkglist
        - yay -Qqm >> $HOME/pkglist
      after:
        - echo "Erasing package list"
        - rm $HOME/pkglist
```

The `~/.autorestic.lock.yml` file looks like this, if you need it:

```yaml
running: false
```

**Comment by Extarys** [comment]
I don't want to spam saying "same!" but I thought I would give my context here as well as I installed this for the first time today. No backups were done yet.

I have this exact output using arm64 binary on a Pi 4 (64 bit Ubuntu) with the following config:
```
locations:
  vaultwarden:
    from: /data/vaultwarden
    to: nas
    hooks:
      before:
        - "docker exec -i postgres /bin/bash -c "PGPASSWORD=something pg_dump --username backup vaultwarden" > vaultwarden.sql"
    cron: '0 */4 * * *'
    options:
      forget:
        keep-last: 5 # always keep at least x snapshots
        keep-hourly: 1 # keep x last hourly snapshots
        keep-daily: 2 # keep x last daily snapshots
        keep-weekly: 1 # keep x last weekly snapshots
        keep-monthly: 3 # keep x last monthly snapshots
        keep-yearly: 2 # keep x last yearly snapshots
        keep-within: '2w' # keep snapshots from the last x weeks

backends:
  nas:
    type: local
    path: /mnt/NASBackup
```

```
$ autorestic info
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x35e148]

goroutine 1 [running]:
github.com/cupcakearmy/autorestic/internal.(*Config).Describe(0x0)
        /home/runner/work/autorestic/autorestic/internal/config.go:62 +0x28
github.com/cupcakearmy/autorestic/cmd.glob..func7(0x700320, 0x737f28, 0x0, 0x0)
        /home/runner/work/autorestic/autorestic/cmd/info.go:12 +0x24
github.com/spf13/cobra.(*Command).execute(0x700320, 0x737f28, 0x0, 0x0, 0x700320, 0x737f28)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x1d0
github.com/spf13/cobra.(*Command).ExecuteC(0x6ff1a0, 0x6c0278, 0x4c2170, 0x4b4f00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x268
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cupcakearmy/autorestic/cmd.Execute()
        /home/runner/work/autorestic/autorestic/cmd/root.go:33 +0x30
main.main()
        /home/runner/work/autorestic/autorestic/main.go:41 +0x24
```

I know I shouldn't (probably) put the postgres password in there but I have no idea where to put it XD

**Comment by ethindp** [comment]
So I ran gocritic on both cobra and autorestic and it only found minor problems. Nothing about pointer issues. I've also fiddled with the code a bit but I can't seem to fix the problem. And I'm not even really sure what's causing it.

**Comment by jontyms** [comment]
I had this problem when pointing to a non existent file

**Comment by cupcakearmy** [comment]
Sry for taking so long. @ethindp could you try to replicate again with the latest version? I added some more checks when loading the config file.

**Comment by Extarys** [comment]
For me this is fixed. I installed the latest version and it works.

**Comment by cupcakearmy** [comment]
I'll close then, feel free to reopen if anything should arise

**Comment by ethindp** [comment]
This issue still occurs for me. It appears to occur when running as root (I back up folders like /boot and /etc, so I need to run autorestic as root).

**Comment by whysthatso** [comment]
@ethindp i'm getting the error if i do not explicitly add `--config /path/to/autorestic.yml` as i have a non-default filename (no prefixed dot)

**Comment by cupcakearmy** [comment]
@ethindp seems like a permissions thing? could you try reading the config file as root? with `su` or whatever your OS supports.

@whysthatso is there some more information? are you running the latest version? I tried to replicate but could not get a pointer exeption. If there are issues with loading the config file autorestic should say something like `Error: config could not be loaded/found`

**Comment by ethindp** [comment]
@cupcakearmy Yeah, it worked when running as root. I'm not sure why that's even happening -- I'd expect permissions errors to be handled gracefully, but I also get the feeling that this has nothing to do with autorestic at all, as I mentioned previously if I remember right. To fix it I had to alter the permissions to root on the config.

**Comment by cupcakearmy** [comment]
> @cupcakearmy Yeah, it worked when running as root. I'm not sure why that's even happening -- I'd expect permissions errors to be handled gracefully, but I also get the feeling that this has nothing to do with autorestic at all, as I mentioned previously if I remember right. To fix it I had to alter the permissions to root on the config.

Ok, The nil pointer still is weird, but i can't reproduce it. If I make the config unreadable by autorestic it exits cleanly reporting that it cannot load the config.

**Comment by whysthatso** [comment]
sorry for the late reply, here some context:


```
root@nas:~# mv .autorestic.yml autorestic.yml
root@nas:~# autorestic
Documentation: https://autorestic.vercel.app

Usage:
  autorestic [command]

Available Commands:
  backup      Create backups for given locations
  check       Check if everything is setup
  completion  Generate completion script
  cron        Run cron job for automated backups
  exec        Execute arbitrary native restic commands for given backends
  forget      Forget and optionally prune snapshots according the specified policies
  help        Help about any command
  info        Show info about the config
  install     Install restic if missing
  restore     Restore backup for location
  uninstall   Uninstall restic and autorestic
  upgrade     Upgrade autorestic and restic

Flags:
      --ci                  CI mode disabled interactive mode and colors and enables verbosity
  -c, --config string       config file (default is $HOME/.autorestic.yml or ./.autorestic.yml)
  -h, --help                help for autorestic
      --restic-bin string   specify custom restic binary (default "restic")
  -v, --verbose             verbose mode
      --version             version for autorestic

Use "autorestic [command] --help" for more information about a command.
root@nas:~# autorestic check
Error: config could not be loaded/found
root@nas:~# autorestic backup
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x77ab99]

goroutine 1 [running]:
github.com/cupcakearmy/autorestic/internal.GetAllOrSelected(0x0, 0x0)
        /home/runner/work/autorestic/autorestic/internal/config.go:205 +0x99
github.com/cupcakearmy/autorestic/cmd.glob..func1(0xb4cbe0, {0x829724, 0x0, 0x0})
        /home/runner/work/autorestic/autorestic/cmd/backup.go:22 +0x85
github.com/spf13/cobra.(*Command).execute(0xb4cbe0, {0xb877b8, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xb4d0e0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cupcakearmy/autorestic/cmd.Execute()
        /home/runner/work/autorestic/autorestic/cmd/root.go:34 +0x25
main.main()
        /home/runner/work/autorestic/autorestic/main.go:41 +0x1c

root@nas:~# autorestic --version
autorestic version 1.5.0

root@nas:~# uname -a
Linux nas 4.4.180+ #41890 SMP Fri Jun 25 02:42:35 CST 2021 x86_64 GNU/Linux synology_apollolake_918+

```

**Comment by cupcakearmy** [comment]
For me it's just spits out "cannot lock before reading config location" if i rename the default config. Really not quite sure how this is happening. If someone has a clue I would be happy to fix it.

**Comment by david-boles** [comment]
Hi, not sure if this is related but it might be a clue? I accidentally mistyped:
```
$ sudo autorestic exec -ac -- snapshots
```
instead of:
```
$ sudo autorestic exec -av -- snapshots
```
and got:
```
Using lock:	 .autorestic.lock.yml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x77aa23]

goroutine 1 [running]:
github.com/cupcakearmy/autorestic/internal.GetAllOrSelected(0x0, 0x1)
	/home/runner/work/autorestic/autorestic/internal/config.go:201 +0x43
github.com/cupcakearmy/autorestic/cmd.glob..func5(0xb4ed60, {0xc00022a180, 0x1, 0x3})
	/home/runner/work/autorestic/autorestic/cmd/exec.go:19 +0x9e
github.com/spf13/cobra.(*Command).execute(0xb4ed60, {0xc00022a150, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xb4e0e0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cupcakearmy/autorestic/cmd.Execute()
	/home/runner/work/autorestic/autorestic/cmd/root.go:34 +0x25
main.main()
	/home/runner/work/autorestic/autorestic/main.go:41 +0x1c
```
If I type the command correctly it still works fine.

I installed it today using grep piped to bash as root (above commands were run as user). I did install and uninstall it a couple of times and start some backups before running into this accidentally.

**Comment by cupcakearmy** [comment]
Ahhh I see.
So the `-c` specifies a config. Probably a weird parsing then goes on.

**Comment by cupcakearmy** [comment]
Is this still relevant?

**Comment by ethindp** [comment]
I think so, but I haven't tried it in some time. I believe its a bug in an upstream dependency, not in autorestic itself.

**Comment by cupcakearmy** [comment]
Ok, will close the issue then. Feel free to reopen if needed
