### ISSUE TITLE
Operation fails when a backend is not available even if not selected

### ISSUE THREAD

**Issue by YacineSahli** [cupcakearmy/autorestic#90]
**Describe the bug**
command fails because it's trying to another another local backend wich is not currently connected

**Expected behavior**
I would expect that only the backend passed with the `-b` flag are checked so that the operation does not fail if another backend is not available.

**Additional context**
In my case, I have a repo located on a external HDD which is not always connected.
Even if I take a backup that is not selecting this repo, it's trying to access it and fails.

**Comment by cupcakearmy** [comment]
Should be fixed in 1.1.2.
Feel free to reopen if not :)

**Comment by YacineSahli** [comment]
I just tried and there is still a problem.
It's trying to open the config file located in the repo but it should not check config files of all repo when specifying one backend.

**Comment by YacineSahli** [comment]
Also, if i have two destinations backend and one of them is down, I would expect the backup to continue properly for the second backend.
For now, the backup will not happend if any of the destination backend is down.

**Comment by cupcakearmy** [comment]
What version are you using?

**Comment by YacineSahli** [comment]
1.1.2

**Comment by cupcakearmy** [comment]
> Also, if i have two destinations backend and one of them is down, I would expect the backup to continue properly for the second backend.
> For now, the backup will not happend if any of the destination backend is down.

That's how it should be working and at least does for me.
Just to clarify: all commands or some specific ones?

**Comment by YacineSahli** [comment]
For example using `restic backup -l home`
The home location has 2 backend, one remote on onedrive and one on a local usb drive that is not always connected.
If the usb drive is not connected I get this.

Backend: onedrive
Fatal: unable to open config file: Stat: stat /run/media/user/backup/restic-repo/config: no such file or directory
Is there a repository at the following location?
/run/media/user/backup/restic-repo

Done
0
Error: 1 errors were found
